# -*- coding: utf-8 -*-
"""armstrong&PalindromeNumber2string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TlmlY5kESmLpiUMiKGarvlRHzjhoURn
"""

userInputoriginal=int(input("enter a number to check if it's armstrong or not:"))

userInput=str(userInputoriginal)

userInput=list(userInput)



lengthUserInput=len(userInput)

newList=[]
for i in range(0,len(userInput)):
  userInput[i]=int(userInput[i])
  userInput[i]=pow(userInput[i], 3)
  newList.append(userInput[i])
  

summed=sum(newList)
if userInputoriginal==summed:
  print("congrats, you have chosen a armstrong number")
else:
  print("not a armstrong number")

userInputoriginal=int(input("enter a number to check if it's palindrome or not:"))


userInput=str(userInputoriginal)
userInput=list(userInput)

lengthUserInput=len(userInput)

if lengthUserInput%2==0:

  for i in range(0,len(userInput)):
    for j in range(1,(lengthUserInput+1)):

      if userInput[i]==userInput[0-j]:
        print("input number is palindrome")
        print(userInput[i])
        print(userInput[0-j])
        
     
        
      else:
        print("input number is not palindrome")
        print(userInput[i])
        print(userInput[0-j])
      break
    
      
  
        

        
else:
  dividedLengthUserInput=lengthUserInput/2
  halfAddeddividedLengthUserInput=int(dividedLengthUserInput+0.5)
  listifiedHalfAddeddividedLengthUserInput=halfAddeddividedLengthUserInput-1
  userInput.pop(listifiedHalfAddeddividedLengthUserInput)
  print(userInput)
  for i in range(0,len(userInput)):
    for j in range(1,len(userInput)):
      if userInput[i]==userInput[0-j]:
        print("input number is palindrome")
      else:
        print("input number is not palindrome")

userInputoriginal=int(input("enter a number to check if it's palindrome or not:"))


userInput=str(userInputoriginal)
userInput=list(userInput)

lengthUserInput=len(userInput)

def palindromEven(inputList):
  for i in range(0,len(inputList)):
    for j in range(1,(len(inputList)+1)):
      

      if inputList[i]==inputList[0-j]:
        print("input number is palindrome")
        print(inputList[i])
        print(inputList[0-j])
      
        
        
     
        
      else:
        print("input number is not palindrome")
        print(inputList[i])
        print(inputList[0-j])
      break

def palindromOdd(inputList):
  lengthInputList=len(inputList)
  dividedLengthInputList=lengthInputList/2
  halfAddeddividedLengthInputList=int(dividedLengthInputList+0.5)
  listifiedHalfAddeddividedLengthInputList=halfAddeddividedLengthInputList-1
  inputList.pop(listifiedHalfAddeddividedLengthInputList)
  print(inputList)
  for i in range(0,len(inputList)):
    for j in range(1,len(inputList)):
      if inputList[i]==inputList[0-j]:
        print("input number is palindrome")
      else:
        print("input number is not palindrome")



if lengthUserInput%2==0:
  palindromEven(userInput)
else:
  palindromOdd(userInput)



userInputoriginal=int(input())
userInput=str(userInputoriginal)
userInput=list(userInput)
userInput.reverse()
print(userInput)

userInputoriginal=int(input("enter a number to check if it's palindrome or not:"))


userInput=str(userInputoriginal)
userInput=list(userInput)

userInput2breversed=userInput[:]

userInput2breversed.reverse()
print(userInput2breversed)


for i in range(0,len(userInput2breversed)):
  if userInput2breversed[i]==userInput[i]:
    print("input is palindrome")
    print(i)
    break
  else:
    print("input is not palindrome")
    print(i)
    break

userInputoriginal=int(input("enter a number to check if it's palindrome or not:"))


userInput=str(userInputoriginal)
userInput=list(userInput)

userInput2breversed=userInput[:]

userInput2breversed.reverse()

myList=[]
for i in range(0, len(userInput2breversed)): 
    userInput2breversed[i] = int(userInput2breversed[i]) 
    myList.append(userInput2breversed[i])

# print(myList)

def convert(list): 
      
    # Converting integer list to string list 
    s = [str(i) for i in list] 
      
    # Join list items using join() 
    res = int("".join(s)) 
      
    return(res) 
  
reversedUserInput=convert(myList)
# print(reversedUserInput) 

if reversedUserInput==userInputoriginal:
  print("user inputted palindrome")
else:
  print("user's input is not palindrome")

userInputoriginal=input("enter a string to check if it's palindrome or not:")


# userInput=str(userInputoriginal)
userInput=list(userInputoriginal)

userInput2breversed=userInput[:]

userInput2breversed.reverse()



def convert(list): 
      

      
    # Join list items using join() 
    res = ("".join(list)) 
      
    return(res) 
  
reversedUserInput=convert(userInput2breversed)


if reversedUserInput==userInputoriginal:
  print("user inputted palindrome")
else:
  print("user's input is not palindrome")