# -*- coding: utf-8 -*-
"""armstrongNumber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TlmlY5kESmLpiUMiKGarvlRHzjhoURn
"""

userInputoriginal=int(input("enter a number to check if it's armstrong or not:"))

userInput=str(userInputoriginal)

userInput=list(userInput)



lengthUserInput=len(userInput)

newList=[]
for i in range(0,len(userInput)):
  userInput[i]=int(userInput[i])
  userInput[i]=pow(userInput[i], 3)
  newList.append(userInput[i])
  

summed=sum(newList)
if userInputoriginal==summed:
  print("congrats, you have chosen a armstrong number")
else:
  print("not a armstrong number")

