# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SewghL5NWbw71CL44oNU4hjPITNKnqSI
"""

# WAP to print first 30 multiples of 5

for i in range(1,31):
  print(i,"* 5 =",i*5)

def fibonacci(n):
    a = 0
    b = 1
    if n <= 0:
        print("Incorrect input")
    elif n == 1:
        return b
    else:
        for i in range(2,n):
            c = a + b
            a = b
            b = c
        return b
 
# Driver Program
 
print(fibonacci(9))

print("No.1 integer in Fibonacci is 0")
print("No.2 integer in Fibonacci is 1")
for i in range(3,10):
  print("No.",i,"integer in Fibonacci is",i-2)

a=0
b=1
c=a+b
d=b+c
e=c+d
f=d+e
g=e+f
h=f+g
i=g+h
j=h+i

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)

myList=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r']

myList[0]=0
myList[1]=1
print("No. 1 from Fibonacci series is ",myList[0])
print("No. 2 from Fibonacci series is ",myList[1])
for i in range(2,len(myList)):
  myList[i]=myList[i-1]+myList[i-2]
  print("No.",i+1,"from Fibonacci series is ",myList[i])

myList=[]
for j in range(1,11):
  
  myList.append('a'*j)


print(myList)

print('t'*5)

myList=[]
for j in range(1,50):
  
  myList.append('a'*j)

myList[0]=0
myList[1]=1
print("No. 1 from Fibonacci series is ",myList[0])
print("No. 2 from Fibonacci series is ",myList[1])
for i in range(2,len(myList)):
  myList[i]=myList[i-1]+myList[i-2]
  print("No.",i+1,"from Fibonacci series is ",myList[i])

